---
type: super-spine

# BGP defaults
bgp_default_ipv4_unicast: false
bgp_update_wait_install: false
bgp_update_wait_for_convergence: false
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200


super_spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65300
    loopback_ipv4_pool: 192.168.250.0/24
  nodes:
    - name: WAN
      id: 1
      mgmt_ip: 172.100.100.30/24
      uplink_ipv4_pool: 172.31.250.0/24
      uplink_switch_interfaces:
        - Ethernet5
        - Ethernet5
        - Ethernet5
        - Ethernet5
      uplink_switches:
        - DC1_BORDER_LEAF1
        - DC1_BORDER_LEAF2
        - DC2_BORDER_LEAF1
        - DC2_BORDER_LEAF2
      uplink_interfaces:
        - Ethernet1
        - Ethernet2
        - Ethernet3
        - Ethernet4