---
fabric_name: DC1_FABRIC

underlay_routing_protocol: EBGP

overlay_routing_protocol: EBGP

evpn_vlan_aware_bundles: false

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
      password: "vnEaG8gMeQf3d3cN6PktXQ=="

spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_defaults:
        #- update wait-for-convergence
        #- update wait-install
        - no bgp default ipv4-unicast
        - distance bgp 20 200 200
        #- graceful-restart restart-time 300
        #- graceful-restart
  leaf_as_range: 65101-65132
  nodes:
    DC1_SPINE1:
      id: 1
      mgmt_ip: 172.100.100.2/24
    DC1_SPINE2:
      id: 2
      mgmt_ip: 172.100.100.3/24

l3leaf:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65100
    uplink_switches: [DC1_SPINE1, DC1_SPINE2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    evpn_services_l2_only: true
    loopback_ipv4_pool: 192.168.255.0/24
    uplink_ipv4_pool: 172.31.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    bgp_defaults:
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        DC1_LEAF1A:
          id: 1
          mgmt_ip: 172.100.100.4/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        DC1_LEAF1B:
          id: 2
          mgmt_ip: 172.100.100.5/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    DC1_LEAF2:
      bgp_as: 65102
      nodes:
        DC1_LEAF2A:
          id: 3
          mgmt_ip: 172.100.100.6/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        DC1_LEAF2B:
          id: 4
          mgmt_ip: 172.100.100.7/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

