type: l3leaf
custom_structured_configuration_list_merge: append
custom_structured_configuration_vlan_interfaces:
  - name: Vlan110
    description: Tenant_A_OP_Zone_1
    shutdown: false
    ip_address_virtual: 10.1.10.1/24
  - name: Vlan111
    description: Tenant_A_OP_Zone_2
    shutdown: false
    ip_address_virtual: 10.1.11.1/24