---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    enable_mlag_ibgp_peering_vrfs: false
    mac_vrf_vni_base: 10000
    vrfs:
      - name: RED
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 10
          loopback_ip_range: 10.255.10.0/24
        svis:
          - id: 110
            name: VRF_RED_VLAN_110
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 112
            name: VRF_RED_VLAN_112
            enabled: true
            ip_address_virtual: 10.1.12.1/24
      
      - name: BLUE
        vrf_vni: 20
        vtep_diagnostic:
          loopback: 20
          loopback_ip_range: 10.255.20.0/24
        svis:
          - id: 111
            name: VRF_BLUE_VLAN_111
            enabled: true
            ip_address_virtual: 10.1.11.1/24
          - id: 113
            name: VRF_BLUE_VLAN_113
            enabled: true
            ip_address_virtual: 10.1.13.1/24
