---
port_profiles:
  Tenant_A_pod1_clientA:
    mode: trunk
    vlans: "110"
  Tenant_A_pod1_clientB:
    mode: trunk
    vlans: "111"

servers:
  server01:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet3, Ethernet3]
        switches: [DC1_PE11, DC1_PE12]
        profile: Tenant_A_pod1_clientA
        port_channel:
          state: present
          description: PortChannel3
          mode: active
          short_esi: 0101:0102:0033
  server02:
    rack: rack01
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [DC1_PE11, DC1_PE12]
        profile: Tenant_A_pod1_clientB
        port_channel:
          state: present
          description: PortChannel4
          mode: active
          short_esi: 0101:0102:0044
  server03:
    rack: rack02
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet3, Ethernet3]
        switches: [DC1_PE21, DC1_PE22]
        profile: Tenant_A_pod1_clientA
        port_channel:
          state: present
          description: PortChannel3
          mode: active
          short_esi: 0201:0202:0033
  server04:
    rack: rack02
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet4, Ethernet4]
        switches: [DC1_PE21, DC1_PE22]
        profile: Tenant_A_pod1_clientB
        port_channel:
          state: present
          description: PortChannel4
          mode: active
          short_esi: 0201:0202:0044
