---
tenants:
  # Tenant A VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    l2vlans:
      110:
        name: Tenant_A_OP_Zone_1
        tags: [ opzone_pod1 ]
      111:
        name: Tenant_A_OP_Zone_2
        tags: [ opzone_pod1 ]