---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    mac_vrf_vni_base: 10000
    enable_mlag_ibgp_peering_vrfs: false
    vrfs:
      - name: Tenant_A_OP_Zone
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          - id: 110
            name: Tenant_A_OP_Zone_1
            tags:
              - opzone_pod1
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 111
            name: Tenant_A_OP_Zone_2
            tags:
              - opzone_pod1
            enabled: true
            ip_address_virtual: 10.1.11.1/24
          - id: 112
            name: Tenant_A_OP_Zone_3
            tags:
              - opzone_pod2
            enabled: true
            ip_address_virtual: 10.1.12.1/24
          - id: 113
            name: Tenant_A_OP_Zone_4
            tags:
              - opzone_pod2
            enabled: true
            ip_address_virtual: 10.1.13.1/24
